name: calendar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^11.2.0
  google_sign_in: ^6.2.2
  http: ^1.2.1
  convert: ^3.1.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.6
  syncfusion_flutter_calendar: ^20.2.46
  permission_handler: ^10.2.0
  flutter_contacts: ^1.1.9+2
  awesome_notifications: ^0.7.7
  url_launcher: ^6.1.7
  shared_preferences: ^2.1.1
  googleapis_auth: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
